#!/bin/sh
choice=$(man -k . | awk '{print $1}' | dmenu -i -nb '#191919' -nf '#fea63c' -sb '#fea63c' -sf '#191919' -fn 'NotoMonoRegular:bold:pixelsize=14' -p 'Manual PDF:')
xargs man -Tps $choice | zathura - &
