#!/bin/sh

EDITOR="alacritty -e nvim"
declare -a options=(
"alacritty - $HOME/.config/alacritty/alacritty.yml"
"bspwm - $HOME/.config/bspwm/bspwmrc"
"sxhkd keybinds - $HOME/.config/bspwm/sxhkd/sxhkdrc"
"Autostart Script - $HOME/.config/bspwm/autostart.sh"
"NeoVim Config - $HOME/.config/nvim/init.vim"
"NeoVim Snippets - $HOME/.config/nvim/UltiSnips"
"zshrc - $HOME/.zshrc"
"ZSH aliases - $HOME/.zhrc-personal"
)

choice=$(printf '%s\n' "${options[@]}" | dmenu -i -c -l 15 -h 30 -p 'Edit config:')
if [[ "$choice" == "quit" ]]; then
	echo "Program terminated." && exit 1
elif [ "$choice" ]; then
	cfg=$(printf '%s\n' "${choice}" | awk '{print $NF}')
	$EDITOR $cfg
else 
	echo "Program terminated." && exit 1
fi
